version: '3'
services:
  app:
    build: flask
    volumes:
      - app:/app
    ports:
        - 5000:5000
    environment:
        PORT: 5000
        FLASK_DEBUG: 1
  proxy:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app: