version: '3.9'
services:
    app:
        image: python:3.9.10-alpine3.14
        volumes:
            - ./flask/:/usr/src/flask/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
        depends_on:
            - requirements

    requirements:
        image: python:3.9.10-alpine3.14
        volumes:
            - .:/project
        working_dir: /flask
        command: pip install -r requirements.txt