version: '3.9'
services:
    app:
        build: .
        volumes:
            - ./flask/:/usr/src/flask/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1